"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("node:crypto");
const{PATH,AUTH_URL,TOKEN_URL,SCOPES,configuration,seal,unseal,importRange,normalize,createReader}=require("../reddit-ads-readonly");
const{SCHEMA}=require("../reddit-ads-store");
const{home}=require("../reddit-ads-routes");
const{install}=require("../install-reddit-ads");
const{buildPlatforms}=require("../marketing-platform-dashboard");
const key=crypto.randomBytes(32),env={REDDIT_ADS_CLIENT_ID:"client_123",REDDIT_ADS_CLIENT_SECRET:"secret",REDDIT_ADS_TOKEN_KEY:key.toString("base64"),REDDIT_ADS_REDIRECT_URL:`https://example.com${PATH}/callback`},config=configuration(env),period={from:"2026-09-01",to:"2026-09-24"};
const response=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});

test("Reddit configuration is exact and read-only",()=>{assert.equal(SCOPES,"adsread");assert.equal(AUTH_URL,"https://www.reddit.com/api/v1/authorize");assert.equal(TOKEN_URL,"https://www.reddit.com/api/v1/access_token");assert.throws(()=>configuration({...env,REDDIT_ADS_REDIRECT_URL:"https://example.com/wrong"}));});
test("Reddit tokens are authenticated encryption bound to the account",()=>{const value={access_token:"a",refresh_token:"r"},cipher=seal(value,key,"1:acct");assert.deepEqual(unseal(cipher,key,"1:acct"),value);assert.throws(()=>unseal(cipher,key,"2:acct"));});
test("Reddit reporting range is bounded",()=>{assert.deepEqual(importRange(period),period);assert.throws(()=>importRange({from:"2026-01-01",to:"2026-09-01"}));});
test("Reddit report normalization preserves micros and converts cent values",()=>{const rows=normalize([{campaign_id:"c1",date:"2026-09-01",spend:1250000,impressions:100,clicks:4,conversion_purchase_clicks:1,conversion_purchase_views:2,conversion_purchase_total_value:12345,conversion_lead_clicks:1,conversion_lead_views:1,reddit_leads:2}],{id:"a1",currency:"USD",timezone:"UTC"},period);assert.equal(rows[0].cost_micros,"1250000");assert.equal(rows[0].conversion_value,"123.45");assert.equal(rows[0].conversions,"3");assert.equal(rows[0].leads,"4");});
test("Reddit reader uses v3 account discovery and data.metrics report shape",async()=>{const calls=[],fetcher=async(url,options)=>{url=new URL(url);calls.push({url,options});if(url.href===TOKEN_URL)return response({access_token:"token2",refresh_token:"refresh",expires_in:3600});if(url.pathname.endsWith("/me/businesses"))return response({data:[{id:"biz"}],pagination:{}});if(url.pathname.includes("/ad_accounts/query"))return response({data:[{id:"acct",name:"Vivid",currency:"USD",time_zone_id:"America/New_York"}],pagination:{}});if(url.pathname.endsWith("/reports"))return response({data:{metrics:[{campaign_id:"9",date:"2026-09-01",spend:1000000,impressions:10,clicks:1}]},pagination:{}});throw Error(url.href);},reader=createReader({config,fetcher});const token=await reader.exchange("code"),accounts=await reader.accounts(token.access_token),rows=await reader.report(token.access_token,accounts[0],period);assert.equal(rows[0].campaign_id,"9");const report=calls.find(c=>c.url.pathname.endsWith("/reports"));const body=JSON.parse(report.options.body);assert.deepEqual(body.data.breakdowns,["CAMPAIGN_ID","DATE"]);assert.equal(body.data.starts_at,"2026-09-01T00:00:00Z");assert.equal(report.options.headers.Authorization,"Bearer token2");});
test("Reddit schema and UI communicate private read-only evidence",()=>{assert.match(SCHEMA,/dashboard_user_id BIGINT/);assert.match(SCHEMA,/token_ciphertext TEXT NOT NULL/);assert.match(SCHEMA,/reddit_ads_private_daily/);const html=home({configured:true,connections:[],csrf:"x",auto:true});assert.match(html,/Read-only reporting/);assert.match(html,/cannot change campaigns/);});
test("Reddit installer is idempotent",()=>{const source='const { registerTikTokAdsRoutes } = require("./tiktok-ads-routes");\nconst { registerMarketingCommandCenterRoutes } = require("./marketing-command-center-routes");\nregisterMarketingCommandCenterRoutes({app});',once=install(source);assert.equal(install(once),once);assert.match(once,/registerRedditAdsRoutes/);});
test("Reddit evidence renders as a Marketing Center platform",()=>{const evidence={connections:[{id:2,account_name:"Reddit",status:"connected",last_synced_at:new Date()}],rows:[{connection_id:2,campaign_id:"9",campaign_name:"Community",currency_code:"USD",impressions:"100",clicks:"10",cost_micros:"5000000",conversions:"2",leads:"3",conversion_value:"40"}]},platforms=buildPlatforms({scope:{kind:"advertiser",userId:1},range:period,campaigns:[],squareStatus:"Not connected",redditEvidence:evidence,redditEnabled:true});const reddit=platforms.find(p=>p.id==="reddit");assert.equal(reddit.campaignCount,1);assert.equal(reddit.metrics[5][1],"3");assert.match(reddit.note,/not verified Vivid sales/);});
